# CMake generated Testfile for 
# Source directory: /home/andrei/ns-allinone-3.42/ns-3.42/scratch
# Build directory: /home/andrei/ns-allinone-3.42/ns-3.42/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_adr-opt-simulation_working "ns3.42-adr-opt-simulation_working-debug")
set_tests_properties(ctest-scratch_adr-opt-simulation_working PROPERTIES  WORKING_DIRECTORY "/home/andrei/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_adr-opt-simulation_working_advanced "ns3.42-adr-opt-simulation_working_advanced-debug")
set_tests_properties(ctest-scratch_adr-opt-simulation_working_advanced PROPERTIES  WORKING_DIRECTORY "/home/andrei/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.42-scratch-simulator-debug")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/andrei/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_adr_example_adr-example "ns3.42-adr-example-debug")
set_tests_properties(ctest-scratch_adr_example_adr-example PROPERTIES  WORKING_DIRECTORY "/home/andrei/ns-allinone-3.42/ns-3.42/build/scratch/adr_example/" _BACKTRACE_TRIPLES "/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_adr_opt_adr-opt-simulation "ns3.42-adr-opt-simulation-debug")
set_tests_properties(ctest-scratch_adr_opt_adr-opt-simulation PROPERTIES  WORKING_DIRECTORY "/home/andrei/ns-allinone-3.42/ns-3.42/build/scratch/adr_opt/" _BACKTRACE_TRIPLES "/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_demo_minimal_demo_minimal "ns3.42-demo_minimal-debug")
set_tests_properties(ctest-scratch_demo_minimal_demo_minimal PROPERTIES  WORKING_DIRECTORY "/home/andrei/ns-allinone-3.42/ns-3.42/build/scratch/demo_minimal/" _BACKTRACE_TRIPLES "/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.42-scratch-subdir-debug")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/andrei/ns-allinone-3.42/ns-3.42/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/andrei/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/andrei/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
